/* 
# Each new term in the # Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.
 sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

*/

function fibonacci() {
  let a = 1;
  let b = 2;
  let sum_even = 0;

  while (b < 4000000) {
    a = b;
    if (b % 2 === 0) {
      sum_even = sum_even + b;
    }
    b = a + b;
  }

  return sum_even;
}

console.log(fibonacci());
